import "./globals.css";
import Navbar from "@/components/navbar";
export const metadata = {
  title: "Apollo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-row h-full w-full text-white">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
